version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR..
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - /usr/local/bin/aws --version
      - /usr/local/bin/aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Build started as on `date`
      - echo Building the docker image..
      - docker build -t nj-nginx:latest .
      - docker tag nj-nginx:latest public.ecr.aws/q7u0k4q6/nj-nginx:latest
  post_build:
    commands:
      - echo Build completed as on `date`
      - echo Pushing the docker image..
      - docker push public.ecr.aws/q7u0k4q6/nj-nginx:latest
      - printf '[{"name":"nj-nginx","imageUri":"%s"}]' public.ecr.aws/q7u0k4q6/nj-nginx:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - echo done!
artifacts:
  files: imagedefinitions.json
